
select STATE_CODE_EXP,
		YEAR,
		MONTH,
		DAY,
		AXLE_GROUP_EXP,
		SUM(AX_CT_01) as Vehicle_class_1, 
		SUM(AX_CT_02) as Vehicle_class_2, 
		SUM(AX_CT_03) as Vehicle_class_3, 
		SUM(AX_CT_04) as Vehicle_class_4, 
		SUM(AX_CT_05) as Vehicle_class_5, 
		SUM(AX_CT_06) as Vehicle_class_6, 
		SUM(AX_CT_07) as Vehicle_class_7, 
		SUM(AX_CT_08) as Vehicle_class_8, 
		SUM(AX_CT_09) as Vehicle_class_9, 
		SUM(AX_CT_10) as Vehicle_class_10,
		SUM(AX_CT_11) as Vehicle_class_11, 
		SUM(AX_CT_12) as Vehicle_class_12, 
		SUM(AX_CT_13) as Vehicle_class_13, 
		SUM(AX_CT_14) as Vehicle_class_14, 
		SUM(AX_CT_15) as Vehicle_class_15, 
		SUM(AX_CT_16) as Vehicle_class_16, 
		SUM(AX_CT_17) as Vehicle_class_17, 
		SUM(AX_CT_18) as Vehicle_class_18, 
		SUM(AX_CT_19) as Vehicle_class_19, 
		SUM(AX_CT_20) as Vehicle_class_20, 
		SUM(AX_CT_21) as Vehicle_class_21, 
		SUM(AX_CT_22) as Vehicle_class_22, 
		SUM(AX_CT_23) as Vehicle_class_23, 
		SUM(AX_CT_24) as Vehicle_class_24, 
		SUM(AX_CT_25) as Vehicle_class_25, 
		SUM(AX_CT_26) as Vehicle_class_26, 
		SUM(AX_CT_27) as Vehicle_class_27, 
		SUM(AX_CT_28) as Vehicle_class_28, 
		SUM(AX_CT_29) as Vehicle_class_29, 
		SUM(AX_CT_30) as Vehicle_class_30, 
		SUM(AX_CT_31) as Vehicle_class_31, 
		SUM(AX_CT_32) as Vehicle_class_32, 
		SUM(AX_CT_33) as Vehicle_class_33, 
		SUM(AX_CT_34) as Vehicle_class_34, 
		SUM(AX_CT_35) as Vehicle_class_35, 
		SUM(AX_CT_36) as Vehicle_class_36, 
		SUM(AX_CT_37) as Vehicle_class_37, 
		SUM(AX_CT_38) as Vehicle_class_38, 
		SUM(AX_CT_39) as Vehicle_class_39, 
		SUM(AX_CT_40) as Vehicle_class_40
-- INTO sums_all 
from dd_ax  
group by AXLE_GROUP_EXP, DAY, MONTH, YEAR, STATE_CODE_EXP 
ORDER BY STATE_CODE_EXP, YEAR, MONTH, DAY