---
title: "Databases: Stable marriage problem"
author: "Juraj Uhlar"
date: "9/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Stable marriage problem

Sources:
* Wikipedia: https://en.wikipedia.org/wiki/Stable_marriage_problem
* Numberfile: https://www.youtube.com/watch?v=Qcv1IqHWAzg&t
* Rosetta code: https://rosettacode.org/wiki/Stable_marriage_problem

## Example datasets

Before running the algorithm, choose one of these three example datasets and run the appropriate chunk of code.


```{r}
# 3 x 3 dataset
# Source and corrent solution: https://cran.r-project.org/web/packages/matchingR/vignettes/matchingR-intro.html
# (We gave the numbers names for readability)

m.prefs <- data.frame(Tom = c("Kate", "Ashley", "Sara"),
    Bob = c("Sara", "Kate", "Ashley"),
    Roman = c("Sara", "Ashley", "Kate"))


f.prefs <- data.frame(Kate = c("Roman", "Bob", "Tom"),
    Ashley = c("Tom", "Roman", "Bob"),
    Sara = c("Roman", "Bob", "Tom"))

```


```{r}
# 4 x 4 dataset
# Source and correct solution: https://youtu.be/Qcv1IqHWAzg?t=346 (Numberfile)
# (Genders in our code are flipped to match the source data, Numberfile uses woman-proposing version of the alghorithm)

m.prefs <- data.frame(Charlotte = c("Bingley", "Darcy", "Collins", "Whickham"),
    Elizabeth = c("Whickham", "Darcy", "Bingley", "Collins"),
    Jane = c("Bingley", "Whickham", "Darcy", "Collins"),
    Lydia = c("Bingley", "Whickham", "Darcy", "Collins"))


f.prefs <- data.frame(Bingley = c("Jane", "Elizabeth", "Lydia", "Charlotte"),
    Collins = c("Jane", "Elizabeth", "Lydia", "Charlotte"),
    Darcy = c("Elizabeth", "Jane", "Charlotte", "Lydia"),
    Whickham = c("Lydia", "Jane", "Elizabeth", "Charlotte"))

```


```{r}
# 10 x 10 dataset
# Source & correct solution: https://rosettacode.org/wiki/Stable_marriage_problem

m.prefs <- data.frame(abe = c("abi", "eve", "cath", "ivy", "jan", "dee", "fay", "bea", "hope", "gay"),
    bob = c("cath", "hope", "abi", "dee", "eve", "fay", "bea", "jan", "ivy", "gay"),
    col = c("hope", "eve", "abi", "dee", "bea", "fay", "ivy", "gay", "cath", "jan"),
    dan = c("ivy", "fay", "dee", "gay", "hope", "eve", "jan", "bea", "cath", "abi"),
    ed = c("jan", "dee", "bea", "cath", "fay", "eve", "abi", "ivy", "hope", "gay"),
    fred = c("bea", "abi", "dee", "gay", "eve", "ivy", "cath", "jan", "hope", "fay"),
    gav = c("gay", "eve", "ivy", "bea", "cath", "abi", "dee", "hope", "jan", "fay"),
    hal = c("abi", "eve", "hope", "fay", "ivy", "cath", "jan", "bea", "gay", "dee"),
    ian = c("hope", "cath", "dee", "gay", "bea", "abi", "fay", "ivy", "jan", "eve"),
    jon = c("abi", "fay", "jan", "gay", "eve", "bea", "dee", "cath", "ivy", "hope"))


f.prefs <- data.frame(abi = c("bob", "fred", "jon", "gav", "ian", "abe", "dan", "ed", "col", "hal"),
    bea = c("bob", "abe", "col", "fred", "gav", "dan", "ian", "ed", "jon", "hal"),
    cath = c("fred", "bob", "ed", "gav", "hal", "col", "ian", "abe", "dan", "jon"),
    dee = c("fred", "jon", "col", "abe", "ian", "hal", "gav", "dan", "bob", "ed"),
    eve = c("jon", "hal", "fred", "dan", "abe", "gav", "col", "ed", "ian", "bob"),
    fay = c("bob", "abe", "ed", "ian", "jon", "dan", "fred", "gav", "col", "hal"),
    gay = c("jon", "gav", "hal", "fred", "bob", "abe", "col", "ed", "dan", "ian"),
    hope = c("gav", "jon", "bob", "abe", "ian", "dan", "hal", "ed", "col", "fred"),
    ivy = c("ian", "col", "hal", "gav", "fred", "bob", "abe", "ed", "jon", "dan"),
    jan = c("ed", "hal", "gav", "abe", "bob", "jon", "col", "ian", "fred", "dan"))
```

## Implementation

With the dataset defined, run this chunk to compute stable marriages. 


```{r}

males <- colnames(m.prefs)
females <- colnames(f.prefs)

# Define the results table
# EngagedTo = Who the man is currently engaged to
# Choice index = Position of the best possible choice on the mans list of preferences = number of times the man was rejected.
m.results = as.matrix(data.frame(name = males,
                engagedTo = rep("", length(males)),
                choiceIndex = rep(1, length(males)), row.names = males))

# Iterate while there are single men
while (length(m.results[m.results[,"engagedTo"] == "",]) > 0) {
  for (x in males) {
    # only single men with unexplored options can propose
    if(m.results[x, "engagedTo"] == "" && as.numeric(m.results[x, "choiceIndex"]) <= length(females)) {
      # Get preference data from tables
      choiceIndex = as.numeric(m.results[x, "choiceIndex"])
      currentChoice = as.character(m.prefs[[x]][choiceIndex])
      currentChoiceEngagement = m.results[m.results[, "engagedTo"] == currentChoice,"name"]
      
      print(paste0(x," proposes to ", currentChoice, ", their ", choiceIndex, ". choice."))
  
      if (length(currentChoiceEngagement) == 0) {
        # If choice is not engaged, she accepts the proposal
        print(paste0(currentChoice," is not engaged and accepts the proposal from ", x, "."))
        m.results[x, "engagedTo"] = currentChoice
      }
      else {
        # Check who the proposed woman prefers more and accept or reject the proposal
        proposalAccepted = which(f.prefs[[currentChoice]] == x) < which(f.prefs[[currentChoice]] == currentChoiceEngagement)
  
        if(proposalAccepted) {
          m.results[currentChoiceEngagement, "engagedTo"] = "";
          m.results[currentChoiceEngagement, "choiceIndex"] = as.numeric(m.results[currentChoiceEngagement, "choiceIndex"]) + 1
          m.results[x, "engagedTo"] = currentChoice
          
          print(paste0(currentChoice," is engaged to ", currentChoiceEngagement, " but prefers ", x, " and accepts their proposal. ", currentChoiceEngagement, " is single again."))
        } else {
          m.results[x, "choiceIndex"] = as.numeric(m.results[x, "choiceIndex"]) + 1
          print(paste0(currentChoice," is engaged to ", currentChoiceEngagement, " and rejects ", x, "."))
        }
      }
      cat("\n")
    }
  }
}

print("Final results: ")
for(row in 1:nrow(m.results)) {
   print(paste0(m.results[row,"name"]," is married to ", m.results[row, "engagedTo"],", his ", m.results[row, "choiceIndex"],". choice."))
}
```


